# This is a very weird project which is an amalgamation 
# of multiple technologies with no framework.
# It is very hard to create a docker image for this, 
# but I will still try doing so anyways because
# learning from mistakes is very important.

# I have no idea how I was able to do this project
# which is a combination of node, jquery, composer, native php,
# bootstrap, and scss. 

# This project tries to imitate the MVC Architecture.
# Since this project has its own custom structure 
# it is better to copy everything except the following:
# 
# 1. vendor - generated by composer
# 2. node_modules - generated by npm

# I used composer to include the dotenv files required
# to fetch the variables from .env
# 
# I used npm to install the following packages: bootstrap and jquery


## Using multiple images 
FROM node:8
FROM composer:latest

COPY package.json .
COPY composer.json .  

RUN npm install 
RUN composer install 

# Copy the entire contents of the custom project structure
COPY . .

RUN echo "Project initialized!"
RUN echo "Please, run XAMPP and start Apache server"